<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-P57AQ83" ignored="0" name="Personal Loan" tests="2" failures="1" timestamp="2022-03-05T11:37:25 IST" time="0.109" errors="0">
  <testcase name="HDFCLoan" time="0.019" classname="Test.Day4">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at Test.Day4.HDFCLoan(Day4.java:15)
at java.util.ArrayList.forEach(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- HDFCLoan -->
  <testcase name="Iciciloan" time="0.002" classname="Test.Day4"/>
</testsuite> <!-- Personal Loan -->
