package Exception;

public class First {
	
	
			
			public static void main(String[] args) {
				int i=9;
				
				try {
					
				} catch (Exception e) {
					
					System.out.println("you can devide");
				}
				
				System.out.println(i/0);
			}
	}


